---
roles:
  - src: https://github.com/yodaaut/ansible-role-proxmox
    version: awx
    name: yodaaut.proxmox
  - src: https://github.com/yodaaut/ansible-role-locale
    version: awx
    name: yodaaut.locale
  - src: https://github.com/yodaaut/ansible-role-chrony
    version: awx
    name: yodaaut.chrony
collections:
  - community.general
